#region Generated by `terra/node/src/rtc/struct_enumz/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc.LitJson;
using view_t = System.UInt64;
using uint8_t = System.Byte;
using int16_t = System.Int16;

namespace Agora.Rtc
{
    ///
    /// <summary>
    /// Playback mode of music resources.
    /// </summary>
    ///
    public enum MusicPlayMode
    {
        ///
        /// <summary>
        /// 0: Original vocal.
        /// </summary>
        ///
        kMusicPlayModeOriginal = 0,

        ///
        /// <summary>
        /// 1: Accompaniment.
        /// </summary>
        ///
        kMusicPlayModeAccompany = 1,

        ///
        /// <summary>
        /// 2: Lead vocal.
        /// </summary>
        ///
        kMusicPlayModeLeadSing = 2,

    }

    ///
    /// <summary>
    /// Music resource preload state.
    /// </summary>
    ///
    public enum PreloadState
    {
        ///
        /// <summary>
        /// 0: Music resource preload completed.
        /// </summary>
        ///
        kPreloadStateCompleted = 0,

        ///
        /// <summary>
        /// 1: Music resource preload failed.
        /// </summary>
        ///
        kPreloadStateFailed = 1,

        ///
        /// <summary>
        /// 2: Music resource is preloading.
        /// </summary>
        ///
        kPreloadStatePreloading = 2,

        ///
        /// <summary>
        /// 3: Cached music resource has been removed.
        /// </summary>
        ///
        kPreloadStateRemoved = 3,

    }

    ///
    /// <summary>
    /// Request status code of the music content center.
    /// </summary>
    ///
    public enum MusicContentCenterStateReason
    {
        ///
        /// <summary>
        /// 0: Request succeeded.
        /// </summary>
        ///
        kMusicContentCenterReasonOk = 0,

        ///
        /// <summary>
        /// 1: General error with no specific cause.
        /// </summary>
        ///
        kMusicContentCenterReasonError = 1,

        ///
        /// <summary>
        /// 2: Gateway error. Possible reasons include:
        ///  The current Token has expired. Please regenerate the Token.
        ///  The provided Token is invalid. Make sure you are using an RTM Token.
        ///  Network error. Please check your network.
        /// </summary>
        ///
        kMusicContentCenterReasonGateway = 2,

        ///
        /// <summary>
        /// 3: Permission error or music resource does not exist. Make sure your project has enabled the Agora Music Content Center permission. Please [contact technical support](https://ticket.shengwang.cn/).
        /// </summary>
        ///
        kMusicContentCenterReasonPermissionAndResource = 3,

        ///
        /// <summary>
        /// 4: Internal data parsing error. Please [contact technical support](https://ticket.shengwang.cn/).
        /// </summary>
        ///
        kMusicContentCenterReasonInternalDataParse = 4,

        ///
        /// <summary>
        /// 5: Error occurred while loading music resource. Please [contact technical support](https://ticket.shengwang.cn/).
        /// </summary>
        ///
        kMusicContentCenterReasonMusicLoading = 5,

        ///
        /// <summary>
        /// 6: Error occurred while decrypting music resource. Please [contact technical support](https://ticket.shengwang.cn/).
        /// </summary>
        ///
        kMusicContentCenterReasonMusicDecryption = 6,

        ///
        /// <summary>
        /// 7: Internal HTTP error. Please try again later.
        /// </summary>
        ///
        kMusicContentCenterReasonHttpInternalError = 7,

    }

    ///
    /// <summary>
    /// Detailed information about the music chart.
    /// </summary>
    ///
    public class MusicChartInfo
    {
        ///
        /// <summary>
        /// The name of the chart.
        /// </summary>
        ///
        public string chartName;

        ///
        /// <summary>
        /// The ID of the music chart.
        /// </summary>
        ///
        public int id;

        public MusicChartInfo(string chartName, int id)
        {
            this.chartName = chartName;
            this.id = id;
        }
        public MusicChartInfo()
        {
        }

    }

    ///
    /// <summary>
    /// Cache status of music resources.
    /// </summary>
    ///
    public enum MUSIC_CACHE_STATUS_TYPE
    {
        ///
        /// <summary>
        /// 0: Music resource is cached.
        /// </summary>
        ///
        MUSIC_CACHE_STATUS_TYPE_CACHED = 0,

        ///
        /// <summary>
        /// 1: Music resource is being cached.
        /// </summary>
        ///
        MUSIC_CACHE_STATUS_TYPE_CACHING = 1,

    }

    ///
    /// <summary>
    /// Information about cached music resources.
    /// </summary>
    ///
    public class MusicCacheInfo
    {
        ///
        /// <summary>
        /// The ID of the music resource, used to identify the music resource.
        /// </summary>
        ///
        public long songCode;

        ///
        /// <summary>
        /// The cache status of the music resource. See MUSIC_CACHE_STATUS_TYPE.
        /// </summary>
        ///
        public MUSIC_CACHE_STATUS_TYPE status;

        public MusicCacheInfo()
        {
            this.songCode = 0;
            this.status = MUSIC_CACHE_STATUS_TYPE.MUSIC_CACHE_STATUS_TYPE_CACHED;
        }

        public MusicCacheInfo(long songCode, MUSIC_CACHE_STATUS_TYPE status)
        {
            this.songCode = songCode;
            this.status = status;
        }
    }

    ///
    /// @ignore
    ///
    public class MvProperty
    {
        ///
        /// @ignore
        ///
        public string resolution;

        ///
        /// @ignore
        ///
        public string bandwidth;

        public MvProperty(string resolution, string bandwidth)
        {
            this.resolution = resolution;
            this.bandwidth = bandwidth;
        }
        public MvProperty()
        {
        }

    }

    ///
    /// <summary>
    /// Configuration for music climax segment.
    /// </summary>
    ///
    public class ClimaxSegment
    {
        ///
        /// <summary>
        /// Start time of the music climax segment in milliseconds.
        /// </summary>
        ///
        public int startTimeMs;

        ///
        /// <summary>
        /// End time of the music climax segment in milliseconds.
        /// </summary>
        ///
        public int endTimeMs;

        public ClimaxSegment(int startTimeMs, int endTimeMs)
        {
            this.startTimeMs = startTimeMs;
            this.endTimeMs = endTimeMs;
        }
        public ClimaxSegment()
        {
        }

    }

    ///
    /// <summary>
    /// Detailed information about the music resource.
    /// </summary>
    ///
    public class Music
    {
        ///
        /// <summary>
        /// The ID of the music resource, used to identify a music resource.
        /// </summary>
        ///
        public long songCode;

        ///
        /// <summary>
        /// The name of the music resource.
        /// </summary>
        ///
        public string name;

        ///
        /// <summary>
        /// The name of the singer.
        /// </summary>
        ///
        public string singer;

        ///
        /// <summary>
        /// The download URL of the music resource poster.
        /// </summary>
        ///
        public string poster;

        ///
        /// <summary>
        /// The release time of the music resource.
        /// </summary>
        ///
        public string releaseTime;

        ///
        /// <summary>
        /// Total duration of the music resource (in seconds).
        /// </summary>
        ///
        public int durationS;

        ///
        /// <summary>
        /// The type of music resource:
        ///  1: Mono track with accompaniment on the left channel and original vocals on the right channel.
        ///  2: Mono track with accompaniment only.
        ///  3: Mono track with original vocals only.
        ///  4: Multi-track audio.
        /// </summary>
        ///
        public int type;

        ///
        /// <summary>
        /// Whether the song supports singing score:
        ///  1: The song supports singing score.
        ///  2: The song does not support singing score.
        /// </summary>
        ///
        public int pitchType;

        ///
        /// <summary>
        /// The number of lyrics in the song.
        /// </summary>
        ///
        public int lyricCount;

        ///
        /// <summary>
        /// Supported lyric formats:
        ///  0: xml format.
        ///  1: lrc format.
        /// </summary>
        ///
        public int[] lyricList;

        ///
        /// <summary>
        /// The number of climax segments.
        /// </summary>
        ///
        public int climaxSegmentCount;

        ///
        /// <summary>
        /// List of music climax segments. See ClimaxSegment.
        /// </summary>
        ///
        public ClimaxSegment[] climaxSegmentList;

        ///
        /// @ignore
        ///
        public int mvPropertyCount;

        ///
        /// @ignore
        ///
        public MvProperty[] mvPropertyList;

        public Music(long songCode, string name, string singer, string poster, string releaseTime, int durationS, int type, int pitchType, int lyricCount, int[] lyricList, int climaxSegmentCount, ClimaxSegment[] climaxSegmentList, int mvPropertyCount, MvProperty[] mvPropertyList)
        {
            this.songCode = songCode;
            this.name = name;
            this.singer = singer;
            this.poster = poster;
            this.releaseTime = releaseTime;
            this.durationS = durationS;
            this.type = type;
            this.pitchType = pitchType;
            this.lyricCount = lyricCount;
            this.lyricList = lyricList;
            this.climaxSegmentCount = climaxSegmentCount;
            this.climaxSegmentList = climaxSegmentList;
            this.mvPropertyCount = mvPropertyCount;
            this.mvPropertyList = mvPropertyList;
        }
        public Music()
        {
        }

    }

    ///
    /// <summary>
    /// Settings for the music content center.
    /// </summary>
    ///
    public class MusicContentCenterConfiguration
    {
        ///
        /// <summary>
        /// The App ID of the project with the content center enabled.
        /// </summary>
        ///
        public string appId;

        ///
        /// <summary>
        /// The RTM Token used for authentication when using the music content center.
        ///  Agora recommends using AccessToken2 for authentication. See [Deploy Token Server](https://doc.shengwang.cn/doc/rtm2/android/user-guide/token/token-generation). When generating the Token, pass a String type mccUid to uid.
        ///  When your Token is about to expire, you can call RenewToken to provide a new Token.
        /// </summary>
        ///
        public string token;

        ///
        /// <summary>
        /// The user ID for using the music content center. This ID can be the same as the uid used when joining an RTC channel, but it must not be 0.
        /// </summary>
        ///
        public long mccUid;

        ///
        /// <summary>
        /// The number of music resources that can be cached, with a maximum of 50.
        /// </summary>
        ///
        public int maxCacheSize;

        ///
        /// @ignore
        ///
        public string mccDomain;

        public MusicContentCenterConfiguration()
        {
            this.appId = "";
            this.token = "";
            this.mccUid = 0;
            this.maxCacheSize = 10;
            this.mccDomain = "";
        }

        public MusicContentCenterConfiguration(string appid, string token, long id, int maxSize = 10, string apiurl = "")
        {
            this.appId = appid;
            this.token = token;
            this.mccUid = id;
            this.maxCacheSize = maxSize;
            this.mccDomain = apiurl;
        }

    }

}
